---
rvm: 
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
env:
  matrix:
  - PUPPET_VERSION="~> 2.7"
  - PUPPET_VERSION="~> 3.3"
  - PUPPET_VERSION="> 3.3"

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 2.7"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7"
    - rvm: ruby-head
      env: PUPPET_VERSION="~> 2.7"
    - rvm: ruby-head
      env: PUPPET_VERSION="~> 3.3"
